# -*- coding: utf-8 -*-
{
    "name": "Event Management",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated advanced module",
    "description": "This is an autogenerated advanced module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "views/event_management_views.xml"
    ],
    "demo": [
        "demo/event_management_data.xml"
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}